/*
# IELTS / TELC Exam Platform — Initial Schema

## Overview
Full schema for an IELTS and TELC language exam practice SaaS platform.
Custom session-based auth (not Supabase Auth) — all DB access is via the
service role key from the Python backend; RLS is enabled on every table to
block direct anon/frontend access.

## Tables

### users
Stores registered users. `user_id` is a custom TEXT PK generated by the
backend (format: `user_{12hex}`). Includes Stripe customer ID and
subscription JSONB blob.

### user_sessions
Session tokens issued by the backend after Emergent OAuth. 7-day TTY.
Indexed on `session_token` for fast auth lookups.

### exams
Stores generated IELTS/TELC exams. All module content (listening, reading,
writing, speaking for IELTS; hoeren, lesen, schreiben, sprechen,
sprachbausteine for TELC) stored as JSONB. Audio generation progress
tracked via `status` and `audio_progress`.

### audio_files
Metadata for MP3 audio segments stored in Supabase Storage.
`storage_path` is the object key within the `audio-files` bucket.

### attempts
User exam attempt records. Supports both single-module and full-test modes.
Stores answers and AI-scored results as JSONB.

## Security
- RLS enabled on all tables.
- No permissive policies for anon or authenticated roles —
  all access goes through the Python backend using the service role key,
  which bypasses RLS automatically.
- This protects the tables if the anon key ever leaks to the browser.
*/

CREATE TABLE IF NOT EXISTS users (
    user_id            TEXT PRIMARY KEY,
    email              TEXT UNIQUE NOT NULL,
    name               TEXT,
    picture            TEXT,
    stripe_customer_id TEXT,
    subscription       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS user_sessions (
    id            BIGSERIAL PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    session_token TEXT UNIQUE NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON user_sessions(session_token);

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS exams (
    exam_id         TEXT PRIMARY KEY,
    title           TEXT NOT NULL DEFAULT '',
    pathway         TEXT NOT NULL DEFAULT 'academic',
    exam_type       TEXT NOT NULL DEFAULT 'ielts',
    telc_level      TEXT,
    status          TEXT NOT NULL DEFAULT 'pending_audio',
    audio_progress  INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    created_by      TEXT,
    listening       JSONB NOT NULL DEFAULT '{}'::jsonb,
    reading         JSONB NOT NULL DEFAULT '{}'::jsonb,
    writing         JSONB NOT NULL DEFAULT '{}'::jsonb,
    speaking        JSONB NOT NULL DEFAULT '{}'::jsonb,
    hoeren          JSONB NOT NULL DEFAULT '{}'::jsonb,
    lesen           JSONB NOT NULL DEFAULT '{}'::jsonb,
    schreiben       JSONB NOT NULL DEFAULT '{}'::jsonb,
    sprechen        JSONB NOT NULL DEFAULT '{}'::jsonb,
    sprachbausteine JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_exams_type   ON exams(exam_type);
CREATE INDEX IF NOT EXISTS idx_exams_status ON exams(status);

ALTER TABLE exams ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS audio_files (
    audio_id      TEXT PRIMARY KEY,
    exam_id       TEXT NOT NULL REFERENCES exams(exam_id) ON DELETE CASCADE,
    section_num   INTEGER,
    segment_index INTEGER,
    audio_type    TEXT NOT NULL DEFAULT 'content',
    storage_path  TEXT NOT NULL,
    format        TEXT NOT NULL DEFAULT 'mp3',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audio_exam ON audio_files(exam_id);

ALTER TABLE audio_files ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS attempts (
    attempt_id        TEXT PRIMARY KEY,
    user_id           TEXT NOT NULL REFERENCES users(user_id),
    exam_id           TEXT NOT NULL REFERENCES exams(exam_id),
    module            TEXT NOT NULL,
    mode              TEXT,
    status            TEXT NOT NULL DEFAULT 'in_progress',
    answers           JSONB NOT NULL DEFAULT '{}'::jsonb,
    scores            JSONB,
    module_answers    JSONB NOT NULL DEFAULT '{}'::jsonb,
    module_scores     JSONB NOT NULL DEFAULT '{}'::jsonb,
    modules_completed JSONB NOT NULL DEFAULT '[]'::jsonb,
    current_module    TEXT,
    overall_band      FLOAT,
    started_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_attempts_user   ON attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_attempts_exam   ON attempts(exam_id);
CREATE INDEX IF NOT EXISTS idx_attempts_status ON attempts(status);

ALTER TABLE attempts ENABLE ROW LEVEL SECURITY;
